//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismWpfApplication.Modules.GamesModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrismWpfApplication.Modules.GamesModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Games&gt;
        ///  &lt;Game Id=&quot;Diablo3&quot;&gt;    
        ///    &lt;HeaderImage&gt;pack://application:,,,/DiabloModule;component/Resources/header.png&lt;/HeaderImage&gt;
        ///    &lt;HeaderText&gt;Diablo III&lt;/HeaderText&gt;
        ///    &lt;Name&gt;Diablo III&lt;/Name&gt;
        ///    &lt;BackgroundImage&gt;pack://application:,,,/DiabloModule;component/Resources/background.jpg&lt;/BackgroundImage&gt;
        ///    &lt;Keywords&gt;
        ///      &lt;Keyword&gt;
        ///        Diablo
        ///      &lt;/Keyword&gt;
        ///      &lt;Keyword&gt;
        ///        Maintenance
        ///      &lt;/Keyword&gt;
        ///    &lt;/Keywords&gt;
        ///  &lt;/Game&gt;
        ///  &lt;Game Id=&quot;WoW&quot;&gt;
        ///    &lt;HeaderImage&gt;pack://ap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;News&gt;
        ///  &lt;Article&gt;
        ///    &lt;ArticleType&gt;Major&lt;/ArticleType&gt;
        ///    &lt;Title&gt;Patch 2.2.1&lt;/Title&gt;
        ///    &lt;Content&gt;Announcing the upcoming Diablo III patch&lt;/Content&gt;
        ///    &lt;Image&gt;
        ///      /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAQCAwMDAgQDAwMEBAQEBQkGBQUFBQsICAYJDQsNDQ0L
        ///      DAwOEBQRDg8TDwwMEhgSExUWFxcXDhEZGxkWGhQWFxb/2wBDAQQEBAUFBQoGBgoWDwwPFhYWFhYW
        ///      FhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhb/wAARCAU1B9ADASIA
        ///      AhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA
        ///      A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewsArticles {
            get {
                return ResourceManager.GetString("NewsArticles", resourceCulture);
            }
        }
    }
}
